### ISSUE TITLE
事件 fire 出的 referrer 的值为 undefined。

### ISSUE THREAD

**Issue by curarchy** [Exodia/er-history-locator#4]
如题。
在 `onPopstate` 里给 `currentLocation` 赋值的时候会赋成 `undefined`，导致后面取到的值不对。

**Comment by Exodia** [comment]
bug 原因：hashchange的时候会触发popstate事件，此时的state一直是null的，因此新的url肯定是undefined

**Comment by Exodia** [comment]
resolved by https://github.com/Exodia/er-history-locator/pull/5
